@baseUrl = http://localhost:3000
@baseUrlModule = {{baseUrl}}/api/v1/products
@id = 1


### home
GET {{baseUrl}} HTTP/1.1

### get items
GET {{baseUrlModule}} HTTP/1.1

### get item
GET {{baseUrlModule}}/{{ id }} HTTP/1.1

### create item
POST {{baseUrlModule}} HTTP/1.1
Content-Type: application/json

{
    "name": "New Product 1",
    "description": "Lorem ipsum 1",
    "price": 99.99,
    "category": "Electronics",
    "in_stock": false
}

### update item
PATCH {{baseUrlModule}}/{{ id }} HTTP/1.1
Content-Type: application/json

{
    "name": "New Product 1b",
    "description": "Lorem ipsum 1b",
    "price": 99.99,
    "category": "Electronics",
    "in_stock": true
}

### delete item
DELETE {{baseUrlModule}}/{{ id }} HTTP/1.1
