-- ============================================================
-- CATALOG DATABASE
-- ============================================================

-- Drop existing tables so this script can be run repeatedly.
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;


-- ============================================================
-- USERS
-- ============================================================

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by INTEGER REFERENCES users(id),
    updated_by INTEGER REFERENCES users(id)
);


-- ============================================================
-- PRODUCTS
-- ============================================================

CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    category VARCHAR(255),
    in_stock BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by INTEGER REFERENCES users(id),
    updated_by INTEGER REFERENCES users(id)
);


-- ============================================================
-- REVIEWS
-- ============================================================

CREATE TABLE reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    content TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by INTEGER REFERENCES users(id),
    updated_by INTEGER REFERENCES users(id)
);


-- ============================================================
-- CATEGORIES
-- ============================================================

CREATE TABLE categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL UNIQUE
);


-- ============================================================
-- TASKS
-- ============================================================

CREATE TABLE tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT
);


-- ============================================================
-- USERS DATA
-- ============================================================

INSERT INTO users (
    id,
    name,
    email,
    role,
    created_at,
    updated_at,
    created_by,
    updated_by
)
VALUES
(
    1,
    'Alice Johnson',
    'admin@email.com',
    'ADMIN',
    '2025-10-27T08:30:00Z',
    '2025-10-27T08:30:00Z',
    1,
    1
),
(
    2,
    'Brian Lee',
    'editor@email.com',
    'EDITOR',
    '2025-10-27T08:35:00Z',
    '2025-10-27T08:35:00Z',
    1,
    1
),
(
    3,
    'Catherine Park',
    'user@email.com',
    'USER',
    '2025-10-27T08:40:00Z',
    '2025-10-27T08:40:00Z',
    1,
    1
);


-- ============================================================
-- PRODUCTS DATA
-- ============================================================

INSERT INTO products (
    id,
    name,
    description,
    price,
    category,
    in_stock,
    created_at,
    updated_at,
    created_by,
    updated_by
)
VALUES
(
    1,
    'Smartphone',
    'Latest smartphone with advanced camera and fast processor.',
    999,
    'Electronics, Mobile',
    true,
    '2025-10-27T09:00:00Z',
    '2025-10-27T09:00:00Z',
    2,
    2
),
(
    2,
    'Wireless Earbuds',
    'Noise-cancelling earbuds with clear sound quality.',
    249,
    'Electronics, Audio',
    true,
    '2025-10-27T09:10:00Z',
    '2025-10-27T09:10:00Z',
    2,
    2
),
(
    3,
    'Gaming Console',
    'Next-gen gaming console with ultra-fast load times.',
    499,
    'Electronics, Gaming',
    false,
    '2025-10-27T09:20:00Z',
    '2025-10-27T09:20:00Z',
    2,
    2
),
(
    4,
    'Smart Speaker',
    'Voice-controlled speaker for music and smart home commands.',
    199,
    'Electronics, Audio, Smart Home',
    true,
    '2025-10-27T09:30:00Z',
    '2025-10-27T09:30:00Z',
    2,
    2
),
(
    5,
    'Tablet',
    'Lightweight tablet perfect for browsing and streaming.',
    399,
    'Electronics, Mobile, Tablet',
    true,
    '2025-10-27T09:40:00Z',
    '2025-10-27T09:40:00Z',
    2,
    2
);


-- ============================================================
-- REVIEWS DATA
-- ============================================================

INSERT INTO reviews (
    id,
    product_id,
    content,
    rating,
    status,
    created_at,
    updated_at,
    created_by,
    updated_by
)
VALUES
(
    1,
    1,
    'Camera quality is amazing.',
    5,
    'approved',
    '2025-10-27T10:00:00Z',
    '2025-10-27T10:00:00Z',
    3,
    3
),
(
    2,
    1,
    'Battery lasts long but heats up sometimes.',
    4,
    'pending',
    '2025-10-27T10:05:00Z',
    '2025-10-27T10:05:00Z',
    2,
    2
),
(
    3,
    2,
    'Noise cancelling works great.',
    5,
    'approved',
    '2025-10-27T10:10:00Z',
    '2025-10-27T10:10:00Z',
    3,
    3
),
(
    4,
    2,
    'Sometimes one earbud loses connection.',
    3,
    'rejected',
    '2025-10-27T10:15:00Z',
    '2025-10-27T10:15:00Z',
    2,
    2
),
(
    5,
    3,
    'Loads games super fast.',
    5,
    'approved',
    '2025-10-27T10:20:00Z',
    '2025-10-27T10:20:00Z',
    3,
    3
),
(
    6,
    3,
    'Controller feels a bit cheap.',
    3,
    'pending',
    '2025-10-27T10:25:00Z',
    '2025-10-27T10:25:00Z',
    3,
    3
),
(
    7,
    5,
    'Perfect size for reading and streaming.',
    5,
    'approved',
    '2025-10-27T10:30:00Z',
    '2025-10-27T10:30:00Z',
    2,
    2
),
(
    8,
    5,
    'Battery drains faster than expected.',
    4,
    'pending',
    '2025-10-27T10:35:00Z',
    '2025-10-27T10:35:00Z',
    3,
    3
),
(
    9,
    1,
    'Sleek design, feels premium in hand.',
    5,
    'approved',
    '2025-10-27T10:40:00Z',
    '2025-10-27T10:40:00Z',
    2,
    2
),
(
    10,
    2,
    'Comfortable fit but loses sound occasionally.',
    4,
    'pending',
    '2025-10-27T10:45:00Z',
    '2025-10-27T10:45:00Z',
    3,
    3
);


-- ============================================================
-- CATEGORIES DATA
-- ============================================================

INSERT INTO categories (id, title)
VALUES
(1, 'Electronics'),
(2, 'Books'),
(3, 'Clothing');


-- ============================================================
-- TASKS DATA
-- ============================================================

INSERT INTO tasks (id, title, description)
VALUES
(
    1,
    'Finalize Monthly Report',
    'Compile data, perform analysis, and write the final report for September sales.'
),
(
    2,
    'Review New Project Planning',
    'Go over the timeline and resource allocation for the new product launch project.'
),
(
    3,
    'Conduct Team Meeting',
    'Prepare the agenda, coordinate attendee availability, and lead the weekly progress review meeting.'
);


-- ============================================================
-- SYNC IDENTITY SEQUENCES
-- ============================================================
-- Explicit ids were inserted above, so each table's identity
-- sequence needs to be advanced past the highest seeded id —
-- otherwise the next INSERT without an id would try to reuse id 1.

SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT MAX(id) FROM users));
SELECT setval(pg_get_serial_sequence('products', 'id'), (SELECT MAX(id) FROM products));
SELECT setval(pg_get_serial_sequence('reviews', 'id'), (SELECT MAX(id) FROM reviews));
SELECT setval(pg_get_serial_sequence('categories', 'id'), (SELECT MAX(id) FROM categories));
SELECT setval(pg_get_serial_sequence('tasks', 'id'), (SELECT MAX(id) FROM tasks));


-- ============================================================
-- VERIFY
-- ============================================================

SELECT 'users' AS table_name, COUNT(*) AS row_count FROM users
UNION ALL
SELECT 'products', COUNT(*) FROM products
UNION ALL
SELECT 'reviews', COUNT(*) FROM reviews
UNION ALL
SELECT 'categories', COUNT(*) FROM categories
UNION ALL
SELECT 'tasks', COUNT(*) FROM tasks;