@baseUrl = http://localhost:3011
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc4NzY1NzUxNiwiZXhwIjoxNzg3NjYxMTE2fQ.9nWULFpl1KgjYAuXkgchEYiDKETqWkcvjNCV9amL9N0

### Health check
GET {{baseUrl}}/health


### List tasks
GET {{baseUrl}}/tasks
Authorization: Bearer {{token}}

### List tasks - no token (should 401)
GET {{baseUrl}}/tasks

### Create a task
POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "learn microservices - {{$timestamp}}"
}
